controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    # 关节状态广播器，必须放在 controller_manager 内部
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster 

    pan_position_controller:
      type: position_controllers/JointGroupPositionController

# 位置控制器，与 controller_manager 同级
pan_position_controller:
  ros__parameters:
    joints: 
      - pan_joint
      - tilt_joint
    interface_name: position
    
    